spring:
  #  ??? jdbc ?? db????? jdbc?? ??? mybatis, jpa ? ?? ??? ??? ?
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board
    username: root
    password: 1234
  jpa:
    database: mysql
    #    innoDB(??)?? ??.
    database-platform: org.hibernate.dialect.MariaDBDialect
    #    ddl? ?? ??. ???? ????(??)???. ???? ??? ??? ?? ??
    generate-ddl: true
    #    jpa? ???????, hibernate? jap? ???? ???(???? ??? ??)
    hibernate:
      #    ddl-auto??3?? ??? ??? create??? ?? ???? ?? ? ???? ?? ??? ??(??? ?? ??!).
      #    update? ???? ????? alter? ???? ?????? ??.(?? ????? ? ?? ? ???. ?? ???? ??? ??-??? ?? ??? ????. ??? ?????????? ??????? ??x)
      #    validate? ??DB?? ???? ???? ?????? ??
      ddl-auto: update
    #    ???? ddl,dml?? ???? ???? ??
    show_sql: true

